name: ws_game_server_types
description: Types for game objects sent via a ws_game_server.
version: 0.0.0-a1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  fast_immutable_collections: ^9.1.5
  json_annotation: ^4.8.1

dev_dependencies:
  enspyr_lints: ^0.0.0-a1
  test: ^1.24.3
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
